# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Lint with black
      run: |
        black --check .
    - name: Test with unittest
      run: |
        python -m unittest
  
  docker:
    runs-on: ubuntu-latest

    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image and push
      run: |
        docker login ghcr.io --username=mahi87 --password=${{ secrets.PACKAGES_TOKEN }}
        docker build -t ghcr.io/mahi87/splitdumb:latest . 
        docker push ghcr.io/mahi87/splitdumb:latest 